---
title: "isotope analysis"
author: "Karl Veggerby"
date: 2/11/2022 
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)




```


```{r}


isodat<-"SI_data_for_analysis.csv"
isodat <- here("data/04_clean data", isodat)
isodat <- read_csv(isodat,
                na = c("", "NA"))


# create a summary table to view species counts
isodat_sum<-isodat %>%
    group_by(sample_category) %>%
  summarize(counts = length(sample_category))



main_sources<-filter(isodat,sample_category=="bubble snail"|sample_category=="Japanese mud snail"|sample_category=="oyster gut")

main_sources<-filter(main_sources,habitat_type=="flipbags"|habitat_type=="eelgrass")

ggplot(data = main_sources, aes(x=d13C,y=d15N, colour=habitat_type))+
  geom_point()

```

```{r}
ggplot(data = main_sources, aes(x=d13C,y=d15N, colour=sample_category))+
  geom_point()

ggplot(data = main_sources, aes(x=d13C,y=d15N, colour=location))+
  geom_point()
```


```{r}

bubble_snail<-filter(main_sources,
               sample_category=="bubble snail")

mud_snail<-filter(main_sources,
               sample_category=="Japanese mud snail")
oyster_gut<-filter(main_sources,
              sample_category=="oyster gut")

ggplot(data = bubble_snail, aes(x=d13C,y=d15N, colour=habitat_type))+
  geom_point()

ggplot(data = mud_snail, aes(x=d13C,y=d15N, colour=habitat_type))+
  geom_point()

ggplot(data = oyster_gut, aes(x=d13C,y=d15N, colour=habitat_type))+
  geom_point()

```



```{r}

gut_balls<-filter(isodat,
               sample_category=="clam gut"|
              sample_category=="oyster gut")



ggplot(data = gut_balls, aes(x=d13C,y=d15N, colour=sample_category))+
  geom_point()

```




```{r}

dungeness<-filter(isodat,sample_category=="dungeness crab")

dungeness<-dungeness %>% 
mutate(length_bin = case_when(length_mm>=10 & length_mm<=20 ~ "10-20",
                 length_mm>=21 & length_mm<=30 ~ "21-30",
                 length_mm>=31 & length_mm<=40 ~ "31-40",
                 length_mm>=41 & length_mm<=50 ~ "41-50",
                 length_mm>=51 & length_mm<=60 ~ "51-60",
                 length_mm>=61 & length_mm<=70 ~ "61-70",
                 length_mm>=71 & length_mm<=80 ~ "71-80",
                 length_mm>=81 & length_mm<=90 ~ "81-90",
                 length_mm>=91 & length_mm<=100 ~ "91-100",
                 length_mm>=101 & length_mm<=110 ~ "101-110",
                 length_mm>=111 & length_mm<=170 ~ "111-170"))


ggplot(data = dungeness, aes(x=d13C,y=d15N, colour=length_bin))+
  geom_point()

ggplot(data = dungeness, aes(x=d13C,y=d15N, colour=location))+
  geom_point()
```

```{r}
stickleback<-filter(isodat,sample_category=="stickleback")

stickleback<-stickleback %>% 
mutate(length_bin = case_when(length_mm>=10 & length_mm<=20 ~ "10-20",
                 length_mm>=21 & length_mm<=30 ~ "21-30",
                 length_mm>=31 & length_mm<=40 ~ "31-40",
                 length_mm>=41 & length_mm<=50 ~ "41-50",
                 length_mm>=51 & length_mm<=60 ~ "51-60",
                 length_mm>=61 & length_mm<=70 ~ "61-70",
                 length_mm>=71 & length_mm<=80 ~ "71-80"))


ggplot(data = stickleback, aes(x=d13C,y=d15N, colour=length_bin))+
  geom_point()
ggplot(data = stickleback, aes(x=d13C,y=d15N, colour=location))+
  geom_point()

```



