---
title: "shiner perch from Padilla mixing models with MixSIAR"
author: Karl Veggerby
date: "1/13/2023"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval=FALSE, warning=FALSE,message=FALSE)
#required packages
library(MixSIAR)
library(tidyverse)
library(here)
```


Introduction 

The goal is to run a stable isotope mixing model using the MixSIAR
package [version 3.1.12](https://cran.r-project.org/web/packages/MixSIAR/index.html)

 

load data in
```{r load data in}

#load_mix_data
mix <- load_mix_data(filename=here("data", "04_clean data", "shiner_perch_padilla.csv"),
iso_names=c("d15N","d13C"), factors=NULL,fac_random=NULL,
fac_nested=NULL, cont_effects=NULL)

#load_source_data
source <- load_source_data(filename=here("data", "04_clean data", "sources_padilla.csv"),
source_factors=NULL, conc_dep=FALSE, data_type = "raw", mix)

#Load discrimination data
discr <- load_discr_data(filename=here("data", "04_clean data", "TEF_padilla.csv"), mix)

```

plot isospace
```{r plot isospace}
#Make isospace plot
#plot_data

iso_plot<-plot_data(filename="isospace_plot", plot_save_pdf=FALSE,
          plot_save_png=FALSE, mix,source,discr,return_obj = TRUE)



```
Plot prior
```{r Plot prior}

percent.weight.alpha <- c(1,1) 

plot_prior(percent.weight.alpha, source)
```

run model
```{r run model}

model_filename <- "MixSIAR_model.txt"
resid_err <- TRUE
process_err <-TRUE
write_JAGS_model(model_filename, resid_err, process_err, mix, source)

#run_model
jags.1 <- run_model(run="very long",mix,source,discr,model_filename,
                    alpha.prior = percent.weight.alpha,resid_err,process_err)

 # save model fit so that it can be called up again without having to be run again
  saveRDS(jags.1, here("model_output","shiner_perch", "padilla", "shiner_perch.model.padilla.rds"))



#Process output
 #output_JAGS
output_JAGS(jags.1, mix, source)

# read the model fit back in later to fiddle with plotting
#jags.1<-readRDS(here("model_output", "shiner_perch", "padilla", "shiner_perch.model.no.effect.rds"))

```

